# Generated by Django 6.1.1 on 2026-10-02 03:53

import apps.characters.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=32, validators=[apps.characters.models.validate_race])),
                ('char_class', models.CharField(max_length=32, validators=[apps.characters.models.validate_class])),
                ('strength', models.PositiveSmallIntegerField(default=apps.characters.models.default_stat)),
                ('dexterity', models.PositiveSmallIntegerField(default=apps.characters.models.default_stat)),
                ('wisdom', models.PositiveSmallIntegerField(default=apps.characters.models.default_stat)),
                ('constitution', models.PositiveSmallIntegerField(default=apps.characters.models.default_stat)),
                ('level', models.PositiveSmallIntegerField(default=apps.characters.models.default_level, validators=[django.core.validators.MinValueValidator(1)])),
                ('xp', models.PositiveIntegerField(default=apps.characters.models.default_xp)),
                ('gold', models.PositiveIntegerField(default=apps.characters.models.default_gold)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
