# Generated by Django 6.1.1 on 2026-10-02 03:55

import apps.characters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gold',
            field=models.PositiveBigIntegerField(default=apps.characters.models.default_gold),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp',
            field=models.PositiveBigIntegerField(default=apps.characters.models.default_xp),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='character_level_gte_1'),
        ),
    ]
